export const Words = [
  "C language",
  "C++ language",
  "Java Core",
  "Python(familiar)",
  "Html",
  "Css",
  "JavaScript",
  "React.js",
  "Node.js",
  "Express.js",
  "Api-Integration",

  "C language",
  "C++ language",
  "Java Core",
  "Python(familiar)",
  "Html",
  "Css",
  "JavaScript",
  "React.js",
  "Node.js",
  "Express.js",
  "Api-Integration",

  "C language",
  "C++ language",
  "Java Core",
  "Python(familiar)",
  "Html",
  "Css",
  "JavaScript",
  "React.js",
  "Node.js",
  "Express.js",
  "Api-Integration",

  "C language",
  "C++ language",
  "Java Core",
  "Python(familiar)",
  "Html",
  "Css",
  "JavaScript",
  "React.js",
  "Node.js",
  "Express.js",
  "Api-Integration",

  "C language",
  "C++ language",
  "Java Core",
  "Python(familiar)",
  "Html",
  "Css",
  "JavaScript",
  "React.js",
  "Node.js",
  "Express.js",
  "Api-Integration",
];
